// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zomspbagivhbdyvynuak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvbXNwYmFnaXZoYmR5dnludWFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDAwODMsImV4cCI6MjA3MDg3NjA4M30.UekQABaMb8QMjy-VcPu371iclsSEn7Fcc1YOeKa_WZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});